Resources:
  UserTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      TableName: "Users"

  PlacesTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      KeySchema:
        - AttributeName: place_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: place_id
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        - AttributeName: upvote_count
          AttributeType: N
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      TableName: "Places"
      GlobalSecondaryIndexes:
        - IndexName: top-city-places
          KeySchema:
            - AttributeName: city
              KeyType: HASH
            - AttributeName: upvote_count
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 50
            WriteCapacityUnits: 50
