Resources:
  UserTable:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      KeySchema:
        - AttributeName: userID
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: userID
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 1
      TableName: "Users"

  PlacesTable:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      KeySchema:
        - AttributeName: placeID
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: placeID
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        - AttributeName: upvoteCount
          AttributeType: N
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 1
      TableName: "Places"
      GlobalSecondaryIndexes:
        - IndexName: TopCityPlaces
          KeySchema:
            - AttributeName: city
              KeyType: HASH
            - AttributeName: upvoteCount
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 1
