service: serverless-graphql-dynamo

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}

  serverless-offline:
    port: 4000
  webpackIncludeModules: true

  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: Users
            sources: [seed-data/Users.json]
          - table: Reviews
            sources: [seed-data/Reviews.json]
          - table: Places
            sources: [seed-data/Places.json]

functions:
  graphql:
    handler: lib/handler.graphqlHandler
    role: ServiceRole
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get

resources:
  - ${file(lib/resources/iam-dynamo.yml)}
  - ${file(lib/resources/iam-x-ray.yml)}
  - ${file(lib/resources/dynamo-db.yml)}
  - ${file(lib/resources/s3-bucket.yml)}
  - ${file(lib/resources/cognito-user-pool.yml)}
  - ${file(lib/resources/cognito-identity-pool.yml)}
