service: maposh

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: ${self:custom.profile.${self:custom.stage}}
  region: us-east-1

custom:
  stage: ${opt:stage, self:provider.stage}
  profile:
    prod: prodMaposh
    staging: stagingMaposh
    dev: default

  webpack:
    webpackConfig: webpack.config.js
    packager: "yarn"
    includeModules: true

  serverless-offline:
    port: 4000

  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: Users
            sources: [./src/utils/seed-data/Users.json]
          - table: Places
            sources: [./src/utils/seed-data/Places.json]

functions:
  graphql:
    handler: src/handler.graphqlHandler
    role: ServiceRole
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get

resources:
  - ${file(src/resources/iam-dynamo.yml)}
  - ${file(src/resources/iam-x-ray.yml)}
  - ${file(src/resources/dynamo-db.yml)}
  - ${file(src/resources/cognito-user-pool.yml)}
  - ${file(src/resources/cognito-identity-pool.yml)}

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
