Resources:
  XrayLambdaRolePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "xray-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "xray:PutTraceSegments"
              - "xray:PutTelemetryRecords"
            Resource:
              - "*"
      Roles:
        - Ref: ServiceRole
